
version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: starter
    env_file:
      - .env
    ports:
      - 3000:3000
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: rhazes123
      POSTGRES_USER: rhazes
      POSTGRES_DB: rhazes_app
    ports:
      - 5432:5432