name: Trigger auto deployment for rhazes

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rhazes-AutoDeployTrigger-61a79f00-6bf4-4328-b8b8-e6ceeadb3cf8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RHAZES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RHAZES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RHAZES_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: rhazes.azurecr.io
          registryUsername: ${{ secrets.RHAZES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RHAZES_REGISTRY_PASSWORD }}
          containerAppName: rhazes
          resourceGroup: rhazes-group
          imageToBuild: rhazes.azurecr.io/rhazes:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


